### ISSUE TITLE
[BUG] Add integration tests for Job Scheduler

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/job-scheduler#146]
Job scheduler plugin does not have integration tests. 
This is a common plugin which is consumed by other plugins. We should add integration tests to ensure the plugin works as we expect and run these tests during our release pipeline from https://github.com/opensearch-project/opensearch-build/tree/main/src/test_workflow#integration-tests.

**Comment by downsrob** [comment]
This was merged to main with the linked PR. As it is targeted for 2.1 it will not be backported and used in the 2.0 GA release, if someone would like for it to be included in 2.0, feel free to initiate the backport.
