### ISSUE TITLE
[BUG] Auto-increment workflow missing DCO

### ISSUE THREAD

**Issue by dblock** [opensearch-project/job-scheduler#149]
**Describe the bug**

In https://github.com/opensearch-project/job-scheduler/runs/5590012410?check_suite_focus=true the DCO check has failed. The auto-increment version workflow needs to sign commits.

**Comment by owaiskazi19** [comment]
Auto increment workflow now has DCO check enabled: https://github.com/opensearch-project/job-scheduler/pull/410.
