### ISSUE TITLE
Implement OpenSearch core branching strategy

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/job-scheduler#205]
### Description

Ensure `MAJOR_VERSION.x` branch exists, the `main` branch acts as source of truth effectively working on 2 versions at the same time.

### Related META issue

https://github.com/opensearch-project/opensearch-plugins/issues/142

### Current Behavior

Currently plugins follow a branching strategy where they work on `main` for the next development iteration, effectively working on 2 versions at the same time. This is not always true for all plugins, the release branch or branch pattern is not consistent, the lack of this standardization would limit multiple automation workflows and alignment with core repo. More details on [META ISSUE](https://github.com/opensearch-project/opensearch-plugins/issues/142)

### Proposed solution

Follow OpenSearch [core branching](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#opensearch-branching). Create `1.x` and `2.x` branches, do not create `2.0` as a branch of main, instead create `main -> 2.x -> 2.0`. Maintain working CI for 3 releases at any given time.

**Comment by prudhvigodithi** [comment]
Hey @amitgalitz can you please post an update on this branching strategy?
Thank you
@dblock @bbarani @CEHENKLE

**Comment by amitgalitz** [comment]
Hi @prudhvigodithi I have a PR open to bump main on JS to 3.0.0-SNAPSHOT but there are some failures on BWC. I'm looking into it more, might need some help from @sbcd90 who recently added these tests.

**Comment by dblock** [comment]
The job-scheduler issue was fixed, see https://github.com/opensearch-project/job-scheduler/pull/242.

**Comment by dblock** [comment]
I fixed the bcw issue in https://github.com/opensearch-project/job-scheduler/pull/242.

**Comment by dblock** [comment]
There should be nothing blocking this rn. To close this issue:

- [ ] main is building 3.0
- [ ] 2.x is building next 2.x, which is currently 2.4.0
- [ ] 2.3 is building next 2.3, which is 2.3.1
- [ ] manifests in https://github.com/opensearch-project/opensearch-build/tree/main/manifests include all 3

**Comment by dblock** [comment]
I fixed https://github.com/opensearch-project/job-scheduler/pull/242, so that closes the main part above.

**Comment by bbarani** [comment]
@amitgalitz @minalsha  I have re-tagged this issue to 2.4.0 release. Can you please provide an update on this issue?

**Comment by amitgalitz** [comment]
Main is at 3.0, 2.x at 2.4 and 2.3 at 2.3.1. Also job scheduler is in manifest for 2.3.1, 2.4.0 and 3.0.0. We can close this issue.
