### ISSUE TITLE
Ensure job-scheduler can be a drop-in replacement for job-scheduler working in ODFE 1.13 and ES 7.10.x for v1.0.0

### ISSUE THREAD

**Issue by dblock** [opensearch-project/job-scheduler#22]
Coming from https://github.com/opensearch-project/OpenSearch/issues/671 and https://github.com/opensearch-project/opensearch-plugins/issues/12.

- [x] Renaming Rest APIs
- [x] Renaming Settings 
- [x] Renaming Indices
       https://github.com/opensearch-project/job-scheduler/blob/f2c4874d328cb80fc6148d5a0704421097a6d05d/spi/src/main/java/com/amazon/opendistroforelasticsearch/jobscheduler/spi/utils/LockService.java#L70
- [x] Renaming Namespaces (E.g. com.amazon.opendistroforelasticsearch to org.opensearch)
- [x] Renaming Classes, Methods, Variables 
- [x] Renaming all remaining identifiers (E.g Opendistro to OpenSearch).
- [ ] 100% Backward compatibility with ES v.?
- [ ] Drop in replacement for Opendistro plugins with OpenSearch plugins

**Comment by dblock** [comment]
Settings done, https://github.com/opensearch-project/job-scheduler/pull/20

**Comment by tlfeng** [comment]
I will take care of this today.

**Comment by tlfeng** [comment]
With above PRs merged, 
Rest APIs, variables, namespaces, and remaining identifiers have been renamed.
No classes and methods to be renamed.

**Comment by dblock** [comment]
@tlfeng What's left for this issue?

**Comment by tlfeng** [comment]
Hi dB, Indices renaming and testing in the real scenario are left.

**Comment by dblock** [comment]
We've decided not to rename indices.

Integration tests need to run against rc1 artifact (coming soon). That probably requires a changer in CI.

**Comment by dblock** [comment]
@tlfeng are we done here? close if so

**Comment by tlfeng** [comment]
Hi dB, I think it can be closed. Although you found the 'rc1' qualifier is not declared in the CI workflow (https://github.com/opensearch-project/job-scheduler/issues/32), it doesn't impact the compatibility of the plugin. We can also close after that is resolved.
