### ISSUE TITLE
[BUG] Distribution build failed for 1.4 version

### ISSUE THREAD

**Issue by bbarani** [opensearch-project/job-scheduler#270]
The distribution build for 1.4 OpenSearch artifact is failed due to some issues with Job Scheduler plugin.

https://build.ci.opensearch.org/job/distribution-build-opensearch/6331/

***Received Error***: **Error building job-scheduler, retry with: ./build.sh manifests/1.4.0/opensearch-1.4.0.yml --component job-scheduler**.
                      The distribution build for job-scheduler has failed.
                      Please see build log at https://build.ci.opensearch.org/job/distribution-build-opensearch/6323/consoleFull' --label autocut,v1.4.0 --repo https://github.com/opensearch-project/job-scheduler.git
could not add label: 'v1.4.0' not found

**Comment by joshpalis** [comment]
Closing as recent 1.4.0 opensearch distribution builds for job scheduler has passed
