### ISSUE TITLE
[FEATURE] Make the job scheduler lock index a system index

### ISSUE THREAD

**Issue by bowenlan-amzn** [opensearch-project/job-scheduler#305]
The job scheduler lock index (`.opendistro-job-scheduler-lock`) is used fully internally and shouldn't be changed by user.
If user inadvertently change this index, it could cause jobs to not running anymore.
Making it a system index can protect it from being changed by user.

**Comment by cwperks** [comment]
I don't see any instances of `stashContext` in the code so that would need to be added before the system index can be added in the security plugin. Can I take on this task?
