### ISSUE TITLE
[BUG] The 2.7.0.0 JS jar in wrong maven coordinates.

### ISSUE THREAD

**Issue by prudhvigodithi** [opensearch-project/job-scheduler#374]
**What is the bug?**
JS and JS-SPI are 2 plugins part of the JS repo.
JS-SPI works fine as it only outputs the jars, it goes under https://aws.oss.sonatype.org/content/repositories/releases/org/opensearch/opensearch-job-scheduler-spi/2.7.0.0/ ---> Valid Scenario
JS has both jar and zip, the jar should be under this [URL](https://aws.oss.sonatype.org/content/repositories/releases/org/opensearch/opensearch-job-scheduler/) (missing for 2.7.0.0) and zips under this [URL](https://aws.oss.sonatype.org/content/repositories/releases/org/opensearch/plugin/opensearch-job-scheduler/2.7.0.0/), but with some change it broke and now both jars and zip are under the zips [URL](https://aws.oss.sonatype.org/content/repositories/releases/org/opensearch/plugin/opensearch-job-scheduler/2.7.0.0/) (groupID: `org.opensearch.plugin`)

**How can one reproduce the bug?**
1. clone https://github.com/opensearch-project/opensearch-build
2. Run `./build.sh manifests/3.0.0/opensearch-3.0.0.yml --component OpenSearch`
3. Run `./build.sh manifests/3.0.0/opensearch-3.0.0.yml --component job-scheduler`
4. cd `tar/builds/opensearch/maven/org/opensearch/plugin/opensearch-job-scheduler/3.0.0.0`
5. `ls -ltr | awk '{print $9}'`
```
opensearch-job-scheduler-3.0.0.0-sources.jar.sha1
opensearch-job-scheduler-3.0.0.0.pom.sha512
opensearch-job-scheduler-3.0.0.0.module
opensearch-job-scheduler-3.0.0.0-javadoc.jar.sha512
opensearch-job-scheduler-3.0.0.0.zip.sha1
opensearch-job-scheduler-3.0.0.0.zip.md5
opensearch-job-scheduler-3.0.0.0-sources.jar.sha512
opensearch-job-scheduler-3.0.0.0-sources.jar.md5
opensearch-job-scheduler-3.0.0.0-sources.jar
opensearch-job-scheduler-3.0.0.0.pom.sha1
opensearch-job-scheduler-3.0.0.0.pom.md5
opensearch-job-scheduler-3.0.0.0.module.sha512
opensearch-job-scheduler-3.0.0.0.module.sha256
opensearch-job-scheduler-3.0.0.0.module.sha1
opensearch-job-scheduler-3.0.0.0-javadoc.jar.sha1
opensearch-job-scheduler-3.0.0.0.jar.md5
opensearch-job-scheduler-3.0.0.0.zip
opensearch-job-scheduler-3.0.0.0.jar
opensearch-job-scheduler-3.0.0.0.zip.sha512
opensearch-job-scheduler-3.0.0.0.zip.sha256
opensearch-job-scheduler-3.0.0.0-sources.jar.sha256
opensearch-job-scheduler-3.0.0.0.pom.sha256
opensearch-job-scheduler-3.0.0.0.pom
opensearch-job-scheduler-3.0.0.0.module.md5
opensearch-job-scheduler-3.0.0.0-javadoc.jar.md5
opensearch-job-scheduler-3.0.0.0-javadoc.jar
opensearch-job-scheduler-3.0.0.0.jar.sha256
opensearch-job-scheduler-3.0.0.0.jar.sha1
opensearch-job-scheduler-3.0.0.0-javadoc.jar.sha256
opensearch-job-scheduler-3.0.0.0.jar.sha512
```
6. Notice both jars and zips under the same location.

**What is the expected behavior?**
The Jars of JS should be under `/org/opensearch/opensearch-job-scheduler` (similar to JS-SPI).

NOTE:  This used to work fine with job-scheduler 2.6.0.0,
[JS-jars](https://aws.oss.sonatype.org/content/repositories/releases/org/opensearch/opensearch-job-scheduler/2.6.0.0/)
[JS-zips](https://aws.oss.sonatype.org/content/repositories/releases/org/opensearch/plugin/opensearch-job-scheduler/2.6.0.0/)

**Comment by saratvemulapalli** [comment]
From what I understand each location can only support one packaging type which is either zip or jars.
So to continue publishing jars for JS we need to publish them under `org.opensearch.opensearch-job-scheduler`
This should help in resolving zips.

So JS will have 3 maven co-ordinates:
- `https://aws.oss.sonatype.org/content/repositories/releases/org/opensearch/opensearch-job-scheduler-spi/` - SPI Jars
- `https://aws.oss.sonatype.org/content/repositories/releases/org/opensearch/opensearch-job-scheduler/` - JS Jars (to be fixed)
- `https://aws.oss.sonatype.org/content/repositories/releases/org/opensearch/plugin/opensearch-job-scheduler/` - JS Zips

**Comment by prudhvigodithi** [comment]
That is correct @saratvemulapalli.

**Comment by vibrantvarun** [comment]
@cwperks and I looking are into this

**Comment by gaiksaya** [comment]
Steps to publish to maven central:

1. Check out this repository in local and check out 2.7 branch
2. Verify that 2.7 branch commit is same as 2.7.0.0 tag and backport commit for https://github.com/opensearch-project/job-scheduler/pull/379
3. Run [build.sh script](https://github.com/opensearch-project/job-scheduler/blob/main/scripts/build.sh) from 2.7 branch which will publish all maven artifacts to `artifacts/maven/org/opensearch`
4. Sign the artifacts using OpenSearch signing system
5. Run [maven publish script ](https://github.com/opensearch-project/opensearch-build/blob/main/publish/stage-maven-release.sh) using dir as `artifacts/maven/org/opensearch`

**Comment by gaiksaya** [comment]
Missing artifacts were released using above steps:
https://aws.oss.sonatype.org/content/repositories/releases/org/opensearch/opensearch-job-scheduler/2.7.0.0/
Closing the issue!

**Comment by peterzhuamazon** [comment]
Just to mention that this issue needs to be added to verify before auto publishing:
* https://github.com/opensearch-project/opensearch-build/issues/2928
