### ISSUE TITLE
Compatibility with segment replication

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/job-scheduler#471]
Coming from https://github.com/opensearch-project/job-scheduler/issues/407#issuecomment-1627834721 as a follow up and with core now supporting real time reads for segment replication enabled indices (https://github.com/opensearch-project/OpenSearch/issues/8536), we can revert https://github.com/opensearch-project/job-scheduler/pull/417/ which enforces DOCUMENT replication strategy for lock indices. 

CC @dbwiddis @owaiskazi19 @joshpalis 

Request owners to label this issue with 2.10.0 release.

**Comment by bowenlan-amzn** [comment]
@joshpalis do we want to change this preference to against primary shard?
https://github.com/opensearch-project/job-scheduler/blob/6abaa3c63aecfce6de0c624bda831228b60c3be7/src/main/java/org/opensearch/jobscheduler/sweeper/JobSweeper.java#L392

cc: @dreamer-89

**Comment by dreamer-89** [comment]
> @joshpalis do we want to change this preference to against primary shard?
> 
> https://github.com/opensearch-project/job-scheduler/blob/6abaa3c63aecfce6de0c624bda831228b60c3be7/src/main/java/org/opensearch/jobscheduler/sweeper/JobSweeper.java#L392
> 
> cc: @dreamer-89

@joshpalis @dbwiddis @owaiskazi19 : Can you please confirm @bowenlan-amzn question above ?

**Comment by joshpalis** [comment]
I've raised a [PR](https://github.com/opensearch-project/job-scheduler/pull/483) to set the search preference of the JobSweeper from `_only_local` to `_primary`
