### ISSUE TITLE
Add backwards compatibility tests for automation

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/job-scheduler#53]
Add backwards compatibility tests for the plugin to automate end-to-end upgrade paths for faster releases. Developer documentation for implementing bwc tests and hooking them to CI: https://github.com/opensearch-project/opensearch-plugins/blob/main/TESTING.md#backwards-compatibility-testing

**Comment by praveensameneni** [comment]
closing the issue as the functionality is tested in plugins (e.g. index-management) using job-scheduler.

**Comment by sbcd90** [comment]
closing the issue as pr is merged.
