### ISSUE TITLE
[BUG] job-shceduler compile issue

### ISSUE THREAD

**Issue by ryanqin01** [opensearch-project/job-scheduler#539]
There seems multiple errors when compiling job-scheduler my own with version 2.9.0 and 2.10.0.

command:
./gradlew build

errors:

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':integTest'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:149)

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':opensearch-job-scheduler-spi:compileJava'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:149)

**Comment by ryanqin01** [comment]
how to reproduce:

just compile job scheduler on a clean env. Centos7, linux64

**Comment by prudhvigodithi** [comment]
[Triage]
Hey @ryanqin01 the ci checks also uses `./gradlew build` 
https://github.com/opensearch-project/job-scheduler/blob/main/.github/workflows/ci.yml#L80. Just few weeks It worked for 2.12 release as well https://github.com/opensearch-project/job-scheduler/pull/584#issuecomment-1936313999.
Also you can leverage the [build workflow](https://github.com/opensearch-project/opensearch-build/tree/main/src/build_workflow) from the build system.
Thanks 
@bbarani
