### ISSUE TITLE
[BUG] After removing publishPluginZipPublicationToMavenLocal from exclude list jars are not getting published

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/job-scheduler#583]
**What is the bug?**
Coming from https://github.com/opensearch-project/job-scheduler/pull/581#issuecomment-1935250785. After removing publishPluginZipPublicationToMavenLocal from exclude list jars are not getting published. A quick fix has been added here https://github.com/opensearch-project/job-scheduler/pull/582 which needs to be reverted.

**How can one reproduce the bug?**
1. Follow the changes in the PR: https://github.com/opensearch-project/job-scheduler/pull/581/files 
2. Run scripts/build.sh
3. See the difference as called out [here](https://github.com/opensearch-project/job-scheduler/pull/581#issuecomment-1935250785)

**What is the expected behavior?**
Jars should be published

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by prudhvigodithi** [comment]
Closing this issue as this was part of 2.12.0 release.
Adding @bbarani @peterzhuamazon @cwperks
