### ISSUE TITLE
Release version 1.2

### ISSUE THREAD

**Issue by dblock** [opensearch-project/job-scheduler#66]
Coming from [opensearch-build#567](https://github.com/opensearch-project/opensearch-build/issues/567), release version 1.2. Please follow the following checklist.

### Preparation

- [x] Assign this issue to a release owner.
- [x] Finalize scope and feature set and update [the Public Roadmap](https://github.com/orgs/opensearch-project/projects/1).
- [x] #77

### CI/CD

- [x] Increment version on main to `1.2.0.0`.
- [x] Ensure working and passing CI.
- [x] Re(add) this repo to the [manifest](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.2.0).

### Pre-Release

- [x] Branch and build from a `1.2` branch.
- [x] #90
- [x] #89
- [x] #88

### Release

- [x] Complete [documentation](https://github.com/opensearch-project/documentation-website).
- [x] Gather, review and publish release notes.
- [x] Verify all issued labeled for this release are closed or labelled for the next release.

### Post Release

- [x] Create [a release tag](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#tagging).
- [ ] Suggest improvements to [this template](https://github.com/opensearch-project/opensearch-plugins/templates/release.md).
- [ ] Conduct a postmortem, and publish its results.

**Comment by peternied** [comment]
@opensearch-project/job-scheduler Could we update this ticket to reflect who is assigned to the 1.2 release?

**Comment by peternied** [comment]
@qreshi Until Friday the 12th at noon PST, any tests that use distribution downloader were running against old bits and need to be rerun.  Can you please see if your team was impacted, rerun the tests, and then mark the tests run as completed in https://github.com/opensearch-project/opensearch-build/issues/954?

**Comment by qreshi** [comment]
@peternied Thanks for the heads up. I reran the tests on the `1.2` branch locally and it passes so we should be good.

**Comment by qreshi** [comment]
The template being linked in this issue that asks us to suggest improvements (`https://github.com/opensearch-project/opensearch-plugins/templates/release.md`) doesn't exist. I'll be leaving that step unchecked for now.

**Comment by dblock** [comment]
We have the parent template in https://github.com/opensearch-project/opensearch-build/blob/main/.github/ISSUE_TEMPLATE/release_template.md and are [instructing](https://github.com/opensearch-project/opensearch-build/blob/main/meta/README.md#create-a-release-issue) the release manager to clone the template from the previous version in https://github.com/opensearch-project/opensearch-build/tree/main/meta/templates/releases. Could you please clone the 1.2 into 1.3 and suggest changes?

**Comment by dblock** [comment]
1.2 has shipped a long time ago, closing
