### ISSUE TITLE
[BUG] Job Scheduler Lock index should not use any user templates

### ISSUE THREAD

**Issue by mgodwan** [opensearch-project/job-scheduler#678]
**What is the bug?**
If a user creates an index template on pattern `*`, any mappings, settings get applied to the job scheduler lock index as well. This can cause issues when there is an overlap in field names or dynamic mapping is getting applied.

**How can one reproduce the bug?**
1. Create a template with lock_time mapping set to short
2. Start job scheduler through an ISM policy to create a new job 
3. Job lock acquire will fail due to failure in create index

**What is the expected behavior?**
Job lock should get acquired

**What is your host/environment?**
 - OS: Amazon Linux
 - Plugins ISM, Job Scheduler

**Do you have any screenshots?**
NA

**Do you have any additional context?**
NA

**Comment by cwperks** [comment]
@mgodwan What version of OpenSearch was this seen in? In general, index templates should filter out system indices before trying to create an index.

**Comment by cwperks** [comment]
Fixed with https://github.com/opensearch-project/OpenSearch/pull/16418
